### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by cristhianDt** [sensortower/daterangepicker#42]
How can I change/translate the texts?

**Comment by BlackMambaCH** [comment]
Hi, I just had the same challenge. I did it like this:

All time specifc things with configuration of moment.js (see [MomentJS Customization]https://momentjs.com/docs/#/customization/)
`moment.locale('de');`

Some texts can be overruled within the daterangepicker initialization:
`$('#daterange').daterangepicker({
     minDate: ...,
     maxDate: ...,
     locale: {
         applyButtonTitle: 'Speichern',
         cancelButtonTitle: 'Abbrechen',
         endLabel: 'Ende',
         startLabel: 'Start'
     },
      ...`

And others need to be updated with jQuery:
`var periods = $('.daterangepicker ul.periods > li.period');
var day = periods.eq(0);
var week = periods.eq(1);
var month = periods.eq(2);
var quarter = periods.eq(3);
var year = periods.eq(4);
day.text("Tag");
week.text("Woche");
month.text("Monat");
quarter.text("Quartal");
year.text("Jahr");`

Hope that helps :)

**Comment by cristhianDt** [comment]
Thanks @BlackMambaCH :+1: :smile:
