### ISSUE TITLE
Title Change

### ISSUE THREAD

**Issue by naveensaravanan** [sensortower/daterangepicker#47]
Possible to change title in calendar?
Ex: I want change **"Year"** to **"Cal Year"**

**Comment by BlackMambaCH** [comment]
Hi
You will need to either change the javascript file (daterangepicker.js, search for "Year" and replace it) or you manipulate the DOM, for example with jQuery:
`
var periods = $('.daterangepicker ul.periods > li.period'); 
var year = periods.eq(4);
year.text("Cal Year");
`
Hope that helps :)
