### ISSUE TITLE
Add an option to completely disable custom ranges selector

### ISSUE THREAD

**Issue by petethepig** [sensortower/daterangepicker#5]
Will probably look like this:
![image](https://cloud.githubusercontent.com/assets/662636/11925439/71e7e074-a7cc-11e5-92b8-808f55690f8d.png)

**Comment by petethepig** [comment]
There must be an option to keep the period type selector though
![image](https://cloud.githubusercontent.com/assets/662636/11925465/9f00d9a8-a7cc-11e5-9c10-04b388ea661c.png)

**Comment by guruprasadBlore** [comment]
Hi,

I badly need your help, please read below.

The period selection option is not working for me at all.Below is my piece of code. 
`	$(".daterangepicker-field").daterangepicker({
		 timeZone: 'utc',
		 firstDayOfWeek: 1,
		 minDate: [moment().subtract(30, 'years'), 'inclusive'],
		 maxDate: [moment(), 'inclusive'],
		 startDate: moment().subtract(29, 'days'),
		 endDate: moment(),
		 forceUpdate: true,
		 ranges:{
			 'Last 30 days': [moment().subtract(29, 'days'), moment()],
	         'Last 90 days': [moment().subtract(89, 'days'), moment()],     
		 },
		 single: true, 
		 periods:['month','quarter','year'],
		 period: 'month',
		 standalone: false,
		 anchorElement: null,
		 parentElement: document.body,
		 
	},
		 function (startDate, endDate, period) {
			  $(this).val(startDate.format('L') + ' – ' + endDate.format('L'))
			
	});`
Below is screenshot
<img width="669" alt="my_daterange_picker" src="https://user-images.githubusercontent.com/23524102/31984242-65517ac6-b97e-11e7-98b1-035c237d5131.png">

**Comment by guruprasadBlore** [comment]
I just need a period selector like this.
![image](https://user-images.githubusercontent.com/23524102/31984301-acdc828c-b97e-11e7-87b5-730b0e59ace8.png)
