### ISSUE TITLE
Daterangepicker opens behind the bootstrap modal

### ISSUE THREAD

**Issue by srehmanali** [sensortower/daterangepicker#63]
I'm loving this plugin it has almost all the functionalities and the look is also so decent. I implemented this to my application where user has to select the date in a bootstrap modal. Somehow the picker opens up behind the modal fade screen where user can not interact with the plugin. Is there any way I can resolve this?

Regards and thanks for the great work!

**Comment by brunorafaeI** [comment]
in your css :

> .daterangepicker {
> z-index: 1
> }

**Comment by srehmanali** [comment]
Thanks a lot. It worked.
