### ISSUE TITLE
Uncaught TypeError: $ is undefined

### ISSUE THREAD

**Issue by opcodespace** [sensortower/daterangepicker#66]
Getting uncaught typeError at `$.fn.daterangepicker` . I am using this plugin in wordpress.  jQuery is loaded correctly before this code. 

Any solution?

**Comment by opcodespace** [comment]
Resolved this issue. There was a problem with the jQuery version. After upgrading it is working.

**Comment by sunwenli** [comment]
> Resolved this issue. There was a problem with the jQuery version. After upgrading it is working.

What's the correct version of jQuery? I got this issue too . 
thanks bro

**Comment by sunwenli** [comment]
@opcodespace

**Comment by opcodespace** [comment]
@sunwenli Sorry I cannot remember that. it was less than version 2. I installed jQuery migrate plugin in wp to resolve this issue.
