### ISSUE TITLE
Add checks in Config

### ISSUE THREAD

**Issue by petethepig** [sensortower/daterangepicker#7]
Add checks to prevent typos & such:

``` js
$('input').daterangepicker({period: 'quartre'}); // typo
// should throw an error "invalid period"
```

**Comment by raviji** [comment]
how to choose current month of days?

**Comment by petethepig** [comment]
I'm not sure what you mean. Can you elaborate a little more?

**Comment by raviji** [comment]
i got fixed current month. thnx @petethepig
